### ISSUE TITLE
things to add

### ISSUE THREAD

**Issue by dannguyen** [dannguyen/journalism-syllabi#3]
https://twitter.com/bkeegan/status/953120499629899776

**Comment by dannguyen** [comment]
https://twitter.com/erikhinton/status/875449577159241729

**Comment by amandabee** [comment]
https://ucb-dataj.github.io/2018/

**Comment by dannguyen** [comment]
Paul Bradshaw's data journalism module: 
https://github.com/paulbradshaw/MED7373-Data-Journalism/

**Comment by mirenbz** [comment]
Data Journalism by Andrew Ba Tran: http://andrewbtran.github.io/JRN-418/

**Comment by dannguyen** [comment]
Thanks for the suggestions! Closing this issue so it doesn't look unresolved
